<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="lidar_length" value="0.05" />
    <xacro:property name="lidar_radius" value="0.03" />


    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder length="${lidar_length}" radius="${lidar_radius}"/>
            </geometry>
            <origin xyz="0 0 ${lidar_length/2.0}" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${lidar_length}" radius="${lidar_radius}"/>
            </geometry>
            <origin xyz="0 0 ${lidar_length/2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="0.5" radius="${lidar_radius}" height="${lidar_length}" o_xyz="0 0 ${lidar_length/2.0}" o_rpy="0 0 0" />
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="${base_length/4.0} 0 ${base_height}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="lidar_link">
        <sensor name="gpu_lidar" type="gpu_lidar">
            <update_rate>10</update_rate>
            <topic>scan</topic>
            <gz_frame_id>lidar_link</gz_frame_id>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <!--(max_angle-min_angle)/samples * resolution -->
                        <resolution>1</resolution>
                        <min_angle>-3.14156</min_angle>
                        <max_angle>3.14156</max_angle>
                    </horizontal>
          <!-- Dirty hack for fake lidar detections with ogre 1 rendering in VM -->
          <!-- <vertical>
              <samples>3</samples>
              <min_angle>-0.001</min_angle>
              <max_angle>0.001</max_angle>
          </vertical> -->
                </scan>
                <range>
                    <min>0.05</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
                <frame_id>lidar_link</frame_id>
            </lidar>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>

</robot>